version: "3"
services:
  nginx:
    restart: always
    image: coconicola/nginx_v1
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      # nginux on 80, but map it to 3050
      - "3050:80"
    depends_on:
      - api
      - client
      - socket
  # api is the server, dont call it server because of the configurations in nginx
  api:
    image: coconicola/server_v1
    # so need to build that container
    build:
      # use the dockerfile with our info there
      dockerfile: Dockerfile

      context: ./server
  socket:
    image: coconicola/socket_v1
    # so need to build that container
    build:
      # use the dockerfile with our info there
      dockerfile: Dockerfile

      context: ./socket

  client:
    image: coconicola/client_v1
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      # everything from client should be applied in app folder
      - ./client:/app
