version: "3"
services:
  webapp:
    image: coconicola/webapp
    # so need to build that container
    build:
      # use the dockerfile with our info there
      dockerfile: Dockerfile
      # indiciate the locations, considering compose file is in root
      # then needs to go to server folder to find dockerfile there
      context: ./

    ports:
      - "3000:3000"
